services:
  postgres:
    image: postgres:15-alpine
    container_name: ecom_postgres
    environment:
      POSTGRES_USER: POSTGRES
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432" # Mapped to 5433 to avoid conflict with local DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ecom_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ecom_api
    environment:
      DATABASE_URL: "postgresql://POSTGRES:PASSWORD@postgres:5432/ecommerce?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 8080
      JWT_SECRET: "s3cr3t-k3y-f0r-d3v"
      VNP_TMN_CODE: "TMNCODE"
      VNP_HASH_SECRET: "SECRET"
      VNP_URL: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
      VNP_RETURN_URL: "http://localhost:3000/checkout/success"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ecom_web
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8080/api/v1"
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
